rules:
  excessive-permissions:
    ignore:
      - ci.yaml:5
  ref-confusion:
    ignore:
      - ci.yaml:49

  unpinned-uses:
    config:
      policies:
        "taiki-e/*": ref-pin
        "rust-lang/*": ref-pin
