# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Ignore generated files
ignores:
  - HELP.md
  - CHECKS.md

# Default state for all rules
default: true

# MD033/no-inline-html - Inline HTML
MD033: false

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false
