# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[licenses]
# Allow these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSL-1.0",      # Boost Software License
    "Unicode-3.0",  # Unicode License
    "Unlicense",
]

# Confidence threshold for license detection
confidence-threshold = 0.8